### ISSUE TITLE
Add new entry in Common Code Table C12 to identify NOAA Satellite Operations Facility as a sub-centre for EUMETSAT

### ISSUE THREAD

**Issue by SimonElliottEUM** [wmo-im/CCT#116]

**Comment by SimonElliottEUM** [comment]
Summary and purpose
Addition of a new entry in Common Code Table C-12 to identify NOAA Satellite Operations Facility (NSOF) as a sub-centre of EUMETSAT (for the provision of radio occultation data)

Action proposed
The team is kindly asked to validate the proposed new entry to be included within the next update to the WMO Manual on Codes.

Discussions
EUMETSAT gets radio occultation data (originally from Spire) from NOAA Satellite Operations Facility (NSOF). The data are processed at EUMETSAT before onward dissemination. It is necessary to use the sub-centre identifier to distinguish between data originating from EUMETSAT and from NOAA.

It is proposed to add an entry in Common Code Table C-12 under C-1/11 EUMETSAT (254) as follow:

254 | EUMETSAT Operation Centre | 220 | NOAA Satellite Operations Facility (NSOF)

**Comment by SimonElliottEUM** [comment]
@amilan17 @marijanacrepulja Dear both. If we could squeeze in this super simple addition to CCT C12 in FT 2023-I I would be most grateful. Normally additions to C-12 are purely administrative and not a technical consideration. I hope so here!

**Comment by marijanacrepulja** [comment]
@amilan17 Could you please create branch for this issue. Many thanks.

**Comment by amilan17** [comment]
@SimonElliottEUM -- branch is ready for you to edit.

**Comment by SimonElliottEUM** [comment]
@amilan17 @marijanacrepulja with the help of my colleagues I have edited the branch and committed the change.

**Comment by marijanacrepulja** [comment]
@SimonElliottEUM many thanks for editing the branch. It looks good. @amilan17 could you please verify and move to "Ready for FT approval procedure"

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023](https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023) notes: 

ready for FT

**Comment by jbathegit** [comment]
@SimonElliottEUM per our discussion this morning, EKMI (Copenhagen) also appears to be disseminating Spire data (i.e. radio occultation profiles where the BUFR 0-01-007 satellite identifier is set to a value of 269).  This was a surprise to us, because we expected all European Spire data to originate from EUMS.

If you have a contact at EKMI, could you please reach out to ask them if they're aware they're doing this, and why?  It's causing us a bit of a headache, because we're receiving the same radio occultation profiles from EUMS, but the reported time stamps differ by as much as 2 minutes between EKMI and EUMS, so our automated processing doesn't properly flag all of them as duplicates.

The GTS headers are `IUT[A-L]14 EKMI`  Previously these headers only contained radio occultation from the MetOp-B and C satellites, but now they also contain profiles from Spire satellites, which again we weren't expecting.

**Comment by SimonElliottEUM** [comment]
> 

@jbathegit @amilan17 @marijanacrepulja Thanks Jeff. Rest assured, I am following up this important point already. But for clarity's sake let me restate that this is unrelated to the issue here #116. Your comment concerns European Spire data and Issue #116 concerns Spire data produced by NOAA and redistributed by EUMETSAT.

**Comment by jbathegit** [comment]
Fair enough.  I only posted it here b/c I'd asked the question while we were discussing this issue during our meeting, so I figured it was sufficiently related.  But if you'd rather reply via a separate email chain, then that's fine with me too.

**Comment by SimonElliottEUM** [comment]
> Fair enough. I only posted it here b/c I'd asked the question while we were discussing this issue during our meeting, so I figured it was sufficiently related. But if you'd rather reply via a separate email chain, then that's fine with me too.

@jbathegit No need for further reply - the issue is formally logged at EUMETSAT and we are dealing with it following our normal process.
