### ISSUE TITLE
CCT 05, new codes for DMSP-F01, DMSP-F02, DMSP-F03, DMSP-F04 and GEO-KOMPSAT-2B

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/CCT#130]
### Initial request

ECMWF is proposing new codes for DMSP 1, DMSP 2, DMSP 3, DMSP 4, GEO-KOMPSAT-2B satellite in support to ERA6 and CAMS.

### Amendment details

|Code figure for I6I6I6|Code figure for BUFR (Code table 0 01 007)|Code figure for GRIB Edition 2|    |
|:---:|:---:|:---:|:---:|
|746|746|746|DMSP 1|
|747|747|747|DMSP 2|
|748|748|748|DMSP 3|
|749|749|749|DMSP 4|
|814|814|814|GEO-KOMPSAT-2B|

### Requestor(s)

Marijana Crepulja, Roberto Ribas, Adrien Oyono Owono (all from ECMWF)

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-5

### Expected impact of change

MEDIUM

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.2&3May.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.2&3May.2023) notes: 

@SimonElliottEUM will look at

**Comment by SimonElliottEUM** [comment]
As the DMSP satellites were not in a geostationary orbit the need to have an even decile in CCT-C5. Instead of 234-237, I propose 746-749. This is a set of four contiguous entries with an even decile and fro m a block allocated to the USA. I will use these values (along with 814 for GK2B) in my proposal to the CGMS Group. I hope that is okay with everyone
@amilan17 @marijanacrepulja

**Comment by marijanacrepulja** [comment]
@SimonElliottEUM many thanks for reviewing this proposal. 
I will update it with new proposed numbers.

**Comment by SimonElliottEUM** [comment]
I have passed this to the CGMS Task Group for their consideration. They have until 29 May to comment. So I can confirm by 1 June.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023 notes:
team agrees
