### ISSUE TITLE
use of GRIB and BUFR registers in codes.wmo.int 

### ISSUE THREAD

**Issue by efucile** [wmo-im/CCT#23]
An analysis of the users of codes.wmo.int is required to be able to decide whether to start a regular process of updating GRIB and BUFR entries in the registry. 
The analysis is made with two different approaches.
1. Inspect schemas and code in OGC standards for access to codes.wmo.int
1. Analyse logs in codes.wmo.int to provide information on the user base.

**Comment by tomkralidis** [comment]
Request sent to the OGC MetOcean Domain Working Group mailing list for discussion: http://lists.opengeospatial.org/pipermail/meteo.dwg/2020-October/001972.html

**Comment by tomkralidis** [comment]
Updates/responses:
- http://lists.opengeospatial.org/pipermail/meteo.dwg/2020-October/001973.html
- http://lists.opengeospatial.org/pipermail/meteo.dwg/2020-October/001974.html

**Comment by marqh** [comment]
I have been looking to the analysis of logs for the codes.wmo.int service.  

in terms of read access logs, all that is logged by the service is IP addresses for individual GET requests.  This is fine grained web server logging, without any context on who is at the other end of the IP, nor any information on usage.

We could consider looking at access at some sort of statistical level, with some work.  I can't promise that the work could be prioritised in swift time though.

It would be good to get a sense of value for this? What kind of statistics could add value to this discussion?

**Comment by blchoy** [comment]
If I remember correctly, the discussion was on the popularity of going into the Codes Registry to look for table entries instead of the online documents and if so, there will be more pressing need to update it at a more timely pace.

**Comment by amilan17** [comment]
The codes registry was mentioned briefly in a couple of the recent Task Teams in reference to _potentially_ being a resource for understanding or use in other standards. 

I think we should be asking _how_ can we make the codes registry more useful, because the Code Registry provides immutable URLs to codes defined by WMO standards and it has the potential to enable integration with systems and standards in a modern way. While understanding the current users is always helpful for insight, I feel that if we stop updating the registry with up-to-date GRIB and BUFR entries that we are doing the future of our communities a disservice.

**Comment by tomkralidis** [comment]
echo @amilan17 .  A managed and versioned WMO code list registry will be a valuable resource that can be used/cached by various information communities.

**Comment by blchoy** [comment]
> I think we should be asking how can we make the codes registry more useful, because the Code Registry provides immutable URLs to codes defined by WMO standards and it has the potential to enable integration with systems and standards in a modern way.

We will have to be careful with regard to the expected use of the Codes Registry from different perspectives.  Back in 2013, I raised a question whether the Codes Registry could be used for online validation (see [this](https://github.com/wmo-im/CCT/files/5478842/TT-AvXML-3-Doc17-final.docx) document for details) and the answer at that time was obviously no as that was not the intended use.  So if @marqh could elaborate a bit more on the expected usage of the Code Registry and possible extension they may have already in mind it should greatly help our future discussion.

**Comment by efucile** [comment]
> The codes registry was mentioned briefly in a couple of the recent Task Teams in reference to _potentially_ being a resource for understanding or use in other standards.
> 
> I think we should be asking _how_ can we make the codes registry more useful, because the Code Registry provides immutable URLs to codes defined by WMO standards and it has the potential to enable integration with systems and standards in a modern way. While understanding the current users is always helpful for insight, I feel that if we stop updating the registry with up-to-date GRIB and BUFR entries that we are doing the future of our communities a disservice.

@amilan17 currently we are not updating GRIB and BUFR entries the problem is Should we start doing it?

**Comment by blchoy** [comment]
> @amilan17 currently we are not updating GRIB and BUFR entries the problem is Should we start doing it?

That's why I am asking the expected service level of the Codes Registry.  If it is similar to other documents on the WMO website (i.e. supposed to be used by human) then it is absolutely fine if we take a slightly layback approach in updating and service provision.  If we are going to support machine-to-machine access then the service level should be much higher.  At this point a better understanding of the underlying design concept of the existing Codes Registry could remove mis-understanding.

**Comment by efucile** [comment]
There are two aspects of the issue.
1. Is codes.wmo.int suitable for machine-to-machine?
2. do we have a requirement for GRIB and BUFR codes to be published on codes.wmo.int?
These are two separate issues. The answer to 1. is yes. However, depending on the registry service level this can be done on the live system or on a cached copy or on a static copy of the content. The strategy to be used is up to the user.
The answer to 2 can be controversial. GRIB and BUFR don't have a direct requirement of a codes registry. A machine-readable format is already produced with other means for the use of all the decoding software. The need comes from the use of BUFR tables from other XML schemas and in particular IWXXM. However, with years of experience, we know that this dependency creates issues in the maintenance of the shared (or common) codelists. It is much better for most of the codelist to be clearly owned by a specific representation rather than shared. There are still some codelist that should be shared and most of them are in the Common Code Tables. They are mostly domain agnostic and can be used by several representations. One example is the satellite identifier or the satellite instrument identifier. Those can be common to different representations. Things like present weather and similar are domain and application-specific and must be owned by the specific representation.

**Comment by blchoy** [comment]
> GRIB and BUFR don't have a direct requirement of a codes registry.

This is indeed correct.  GRIB and BUFR are supposed to be self-contained.  The reason why IWXXM is using some of the BUFR code tables is due to historic reason: That BUFR sequences had been defined for some of the aviation reports but before they were formally adopted, the aviation community had abandoned them and start over with XML/GML.  The initial version of IWXXM are using some of the BUFR code tables on the Codes Registry directly but the later ones have switched to their aliases which are under the umbrella of WMO No.306 Vol. I.3.

So the solution for IWXXM is rather simple: (1) Create code tables for WMO No.306 Vol. I.3.  (2) Disconnect the relationship between these code tables and their BUFR counterparts on the Codes Registry.  (3) (Optionally) Deprecate aviation specific BUFR sequences and code tables as necessary.

For code tables (not necessarily the common tables) shared by BUFR sequences under different domains this could be much more difficult.

**Comment by jitsukoh** [comment]
The decision to put GRIB2/BUFR4 tables on the codes registry was made by the Secretariat, and therefore TT-TDCF is not in the position to decide to continue/discontinue. That said, my opinion is:

- The priority should be given to maintain operational codes, for which WMO is responsible. In that sense, the issue of IWXXM's using BUFR4 tables should be resolved, and I support the approach proposed by @blchoy .
- With the condition that the issue of IWXXM's use of BUFR4 tables is resolved, I agree with the opinion that GRIB2/BUFR4 tables in the Codes Registry can be useful for various applications if they are updated properly, as @marqh @amilan17 and @tomkralidis point out, but from ET's point of view, this is an optional activity that can be carried out if resources allow, given that we publish tables in XML format officially.
- I don't think ET at this moment has additional resources available for the optional activity. If the Secretariat decides to support it at the Secretariat resources, there is no reason to stop as far as the consistency with the official Manual is guaranteed, but it is difficult for ET to accept additional workload. 
- In any case, GRIB2/BUFR4 tables on the codes registry without a table version control is not acceptable, because the table version is a fundamental component of TDCF. In that sense, current tables on the registry should be either updated with the right version control or deleted. This is true even if there are applications that are currently using these tables, including OGC MetOcean metadata profile for WCS2.0.

**Comment by efucile** [comment]
I agree with all the points made by Jitsuko. I would like only to add.
1. The choice of publishing GRIB and BUFR tables on codes registry was not only Secretariat. It was made by IPET-DD with the argument that the codes registry complements other ways of publishing the code tables and is not the authoritative source. From that time things evolved and now the codes registry is the authoritative source for WIGOS metadata.
2. The codes registry is one of the various publication means the Secretariat is supporting. We produce pdf, txt, xml, and ttl to be uploaded in the codes registry. The Secretariat should have tools to generate all these formats from the GitHub repository when required. The realization of the tools will require work from the ETs, but as soon as the processes of multiple publication is automated, it should be seamlessly applied by the Secretariat when the approval process is completed.
3. It is true that table version is a vital component of GRIB and BUFR release process, but given that codes registry is only complementary to other publication means it could be sufficient to publish the latest version and state clearly in the codes registry in the form of a disclaimer that the version published is ...

**Comment by tomkralidis** [comment]
Example of value of codes.wmo.int:

As part of our work in the OGC MetOcean Domain Working Group, we are working on a MetOcean best practice profile of the emerging OGC API - Records standard (for search).  This will enable community-based interoperability for weather/climate/water efforts in OGC APIs, in addition to mass market support to lower the barrier to discovery, access, and visualization of our data.

Our initial efforts are based on identifying metadata types for high level classification, to which BUFR Table A was identified and suggested.  In this case, it would be valuable to have (a versioned) Table A on codes.wmo.int.  We do have the [Manual](https://library.wmo.int/doc_num.php?explnum_id=10310) of course but we need something webby.

Having the significant effort over the years by WMO and experts developing the code lists made available in this manner will allow for increased usage beyond the usual suspects (i.e. why should we in OGC create code lists for an API profile when there are solid ones in WMO, which simply to be stood up as an authoritative source for dereferencing).

**Comment by blchoy** [comment]
@tomkralidis: We should be careful when we use the code lists beyond their intended applications.  They are developed to support the respective BUFR sequences or IWXXM schemas and are both domain and application specific.  There is no guarantee that the tables and the respective sequences or schemas will be developed in line with your application; in the worst case when the sequences and schemas are abandoned (we have BUFR sequences for METAR/SPECI and TAF but they were abandoned before having a chance to be used) there will be no further updates to the code lists.

**Comment by tomkralidis** [comment]
@blchoy thanks for the info.  Perhaps this can be part of the assessment of downstream information communities (usual suspects or not), if they find value in using codelists/vocabularies created/managed by other entities/communities?

**Comment by blchoy** [comment]
>  Perhaps this can be part of the assessment of downstream information communities (usual suspects or not), if they find value in using codelists/vocabularies created/managed by other entities/communities?

So this goes back to Enrico's original question: Whether there is a need to expose GRIB and BUFR tables through Codes Registry?  The existing GRIB and BUFR applications are happy without having their tables on the Codes Registry. It is also weird if we expect people use these sequences/tables beyond their intended purposes.  

In view of existing amount of work and team resources, I believe these are valid considerations.

Historically, there used to be an idea to develop generic XML/GML representations for MET entities so that people can reuse these "authoritative" representations in their own domain.  Its development, however, exceeds the limit of the task team as it is not the team's prime objective so there is no further development of the representation right now.  You may want to take a look at its README.md file [here](https://github.com/wmo-im/metce).

Happy to listen to other teams' views.

**Comment by chris-little** [comment]
I am speaking as a WMO/OMM outsider now. It seems to me that the thread above has both strategic and tactical issues to be tackled.
Strategic:
1. The tables of the TDCFs, and TACs, are the semantic underpinnings of potentially many data representations.
2. The content of the tables, maintained by WMO as authoritative, international, multi-lingual statements of its expertise, also form the basis of standardised vocabularies and potentially taxonomies and ontologies, and are WMO's "crown jewels".
3. In the past, other global organisations, both private and public, have encroached upon WMO's domain, especially when it was not showing leadership, or lacked vision, or was just plainly too slow. And they are still trying to do so.
4. Other authoritative global organisations have their own areas of expertise, and publish authoritative data, such as IUPAC for chemistry, BIPM/IERS for time, IOPG/EPSG for (some) coordinate reference systems, IAU for astronomical bodies, UCUM for Unit of Measure, etc. Some are better, some worse, through using a range of mechanisms from plain paper, via PFDs and spreadsheets, to automated machine to machine registries.
5. Nowadays, if you are not a native web inhabitant, you do not exist! OK, slighty extreme, but when soldiers stop using their issued equipment and use that bought in local shops, and satellites are 100 a launch, and a 2400bps telex line is much more expensive than a 10Mb/s link, things have to change. `Se' vogliamo che tutto rimanga com'è bisogna che tutto cambi.`

Tactical:
5. WMO Expert Teams always have too much work to do and too few resources. This should not be a reason to switch off the registries. 
6. Until safety critical applications start using the registries operationally, it is probably better to populate them slowly as resources allow, and until internal Secretariat processes can be optimised.

As an external user, how do I specify authoritative meteorological/hydrographic/oceangraphic definitions in my processes, data formats, searches, queries, retrievals, catalogues and knowledge graphs? How can the private sector do that too?

**Comment by david-i-berry** [comment]
As part of WMO CF regulations we are mandating the use of codes.wmo.int to specify the observed parameter, e.g. see the snippet below form the draft regulations (passed INFCOM-2, E/C and now going to Cg.):

> WMO-CF.5.2.7 The standard_name attribute shall be used when there is an existing definition in the CF conventions.
> 
> WMO-CF.5.2.8 The long_name attribute should be used to describe the content of the variable.
> 
> WMO-CF.5.2.9 The wmo__parameter_uri and wmo__parameter_name attributes shall be used to unambiguously identify the observed/measured parameter being reported.
> 
> WMO-CF.5.2.10 The wmo__parameter_uri shall point to an entry in a codes registry authorized for use within the profile of the data product. The use of codes.wmo.int is authorized for all profiles; individual WMO-CF profiles may additionally define their own list of authorized registries.

We also plan to make use of the codes registry as part of the TT-CDM work. As part of this we really need to improve the use of ontologies and mapping between vocabularies. A good starting point would be equivalence between BUFR, CF NetCDF and the WIGOS code lists.

**Comment by chris-little** [comment]
@david-i-berry It is good to read the above position. 

OGC has already adopted a policy decision to, wherever possible, refer to other authoritative registries for appropriate definitions, such as IOPG/EPSG for some coordinate reference system, and observed properties, which could be WMO or EU INSPIRE controlled vocabularies.
As part of the policy, pending other registries being operational (some are decidedly not, or not even existing), OGC will host definitions in its own registers, with a pointer to the authoritative body (which could even be a postal address).

A current concrete example is the private open source company Geomatys wanting to use a rotated pole grid definition from the GRIB manual. As they are unable to access an authoritative machinable version of the definition frlmWMO, they can use an OGC register definition with a link to the WMO and its Manual on Codes.

Best of luck with the GRIB/CF mapping. The original work was very C(limate) rather than F(orecast) orientated. I think that the message here, and from aviation, is that there will always be several overlapping authoritative sources for any domain.

**Comment by blchoy** [comment]
> I think that the message here, and from aviation, is that there will always be several overlapping authoritative sources for any domain.

Can't agree more.  Could @david-i-berry include aviation when considering improving the use of ontologies and mapping between vocabularies please?  TT-AvData is more than happy to participate.
